apiVersion: apps/v1
kind: Deployment
metadata:
  name: frondend
  namespace: test
spec:
  selector:
    matchLabels:
      app: frondend
  replicas: 1
  template:
    metadata:
      labels:
        app: frondend
    spec:
      containers:
        - name: frondend
          image: 172.29.7.157:85/frontend/frontend-service:<BUILD_TAG>
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frondend
  namespace: test
  labels:
    app: frondend
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 80
  selector:
    app: frondend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frondend
  namespace: test
spec:
  rules:
    - host: frondend.devopsplus.com.cn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frondend
                port:
                  number: 14237
